### ISSUE TITLE
Nested selectors are not recognized

### ISSUE THREAD

**Issue by lonekorean** [posthtml/posthtml-minify-classnames#52]
Thank you for your work on this plugin!

When processing [vanilla CSS nesting selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) with `removeUnfound: true`, it seems that some class names are not recognized, resulting in broken styling.

For example, these selectors:

```css
div {
  &.make-green {
    background-color: #6c6;
  }
}

.excitable {
  &[data-excited="true"] .suffix::before {
    content: '!!!';
  }
}
```

You can [see my test case here](https://codepen.io/lonekorean/pen/zYbqgdM/1911d93c45b12e3c6ee6a47957f6ce3d). The result should be a green box with "!!!" added inside.

This is what I get after processing. You can see that some necessary class names are removed (without being replaced with minified names):

```html
<div class="a" data-excited="true">
  Hello
  <span class=""></span>
</div>
```

```css
body {
  font: 4rem/1 sans-serif;
}

div {
  width: 400px;
  height: 200px;
  margin: 10px;
  background-color: #c66;
}

div {
  &.make-green {
    background-color: #6c6;
  }
}

.a {
  &[data-excited="true"] .suffix::before {
    content: '!!!';
  }
}
```

When I run with `removeUnfound: false` things render correctly (with some class names not minified).
